### PR TITLE
Add new week with several links

### PR DESCRIPTION
**Pull request by forcewake**
1. [RX Over the wire](https://sachabarbs.wordpress.com/2016/12/23/rx-over-the-wire/)
1. [Microsoft Azure Storage Import/Export Announcements](https://azure.microsoft.com/ru-ru/blog/microsoft-azure-storage-import-export-announcements/)
1. [Exploring F# with .NET Core and Kestrel](https://shane.logsdon.io/posts/exploring-fsharp-with-dotnet-core-and-kestrel/)
1. [ReSharper Interactive Tutorials](https://blog.jetbrains.com/dotnet/2016/12/22/resharper-interactive-tutorials/)
1. [Rewriting Hello World according to SOLID in .NET](https://dotnetcodr.com/2016/12/22/rewriting-hello-world-according-to-solid-in-net/)
1. [Introduction to DocumentDB](https://www.infoq.com/presentations/documentdb)
1. [Navigating the Ins and Outs of a Microservice Architecture (MSA)](https://www.infoq.com/articles/navigating-microservices-architecture)
1. [Getting started with ANTLR in C#](https://tomassetti.me/getting-started-with-antlr-in-csharp/)
1. [Functional approaches to dependency injection](http://fsharpforfunandprofit.com/posts/dependency-injection-1/)
1. [Understanding Monads in F#](https://fsharpn00b.blogspot.com.by/2016/12/understanding-monads-in-f.html)
1. [The Traveling Santa Problem… a Neural Network solution](http://www.rickyterrell.com/?p=97)

### CODE REVIEW

**Review by RamanBut-Husaim — APPROVED** [review]

**Review by RamanBut-Husaim — CHANGES_REQUESTED** [review]
@forcewake Please, take a look.

**Comment by RamanBut-Husaim** [comment]
@forcewake Pavel, please add an entry to the top-level [SUMMARY.md](https://github.com/RamanBut-Husaim/dotNetWeekly/blob/master/SUMMARY.md) file.

**Comment by RamanBut-Husaim** [comment]
@forcewake And this [entry](http://aakinshin.net/en/blog/dotnet/perfex-div/) to the runtime section.

**Comment by RamanBut-Husaim** [comment]
@forcewake Thanks!

**Comment by forcewake** [comment]
@RamanBut-Husaim, done.

**Review by RamanBut-Husaim — APPROVED** [review]

**Pull request merged**
